
// Variables
:microprofile-jwt: https://github.com/eclipse/microprofile-jwt-auth/
:mp-jwt-name: Eclipse MicroProfile JWT RBAC

image:https://semaphoreci.com/api/v1/smallrye/smallrye-jwt/branches/master/badge.svg["Semaphore CI", link="https://semaphoreci.com/smallrye/smallrye-jwt"]
image:https://sonarcloud.io/api/project_badges/measure?project=smallrye_smallrye-jwt&metric=alert_status["Quality Gate Status", link="https://sonarcloud.io/dashboard?id=smallrye_smallrye-jwt"]
image:https://img.shields.io/github/license/thorntail/thorntail.svg["License", link="http://www.apache.org/licenses/LICENSE-2.0"]

= SmallRye JWT

SmallRye JWT is a library for implementing the {microprofile-jwt}[{mp-jwt-name}]. Currently it is focused on supporting the MP-JWT 1.1 spec, and primarily deals with the parsing of the JWT string into a JsonWebToken implementation.

In the future, when MP-JWT 2.0 can build on the JSR-375 security APIs, there should be more support for defining the CDI extension and security layer integration.

== Instructions

Compile and install this project:

[source,bash]
----
mvn clean install
----

=== Project structure

* link:implementation[] - Implementation of the {mp-jwt-name} library.
* link:tck[] - Test suite to run the implementation against the {mp-jwt-name} TCK.
* link:docs[] - Project documentation.

=== Links

* http://github.com/smallrye/smallrye-jwt/[Project Homepage]
* {microprofile-jwt}[{mp-jwt-name}]

