:microprofile-jwt: https://github.com/eclipse/microprofile-jwt-auth/
:mp-jwt-name: Eclipse MicroProfile JWT RBAC
:ci: https://github.com/smallrye/smallrye-jwt/actions?query=workflow%3A%22SmallRye+Build%22
:sonar: https://sonarcloud.io/dashboard?id=smallrye_smallrye-jwt

image:https://github.com/smallrye/smallrye-jwt/workflows/SmallRye%20Build/badge.svg?branch=master[link={ci}]
image:https://sonarcloud.io/api/project_badges/measure?project=smallrye_smallrye-jwt&metric=alert_status["Quality Gate Status", link={sonar}]
image:https://img.shields.io/github/license/smallrye/smallrye-jwt.svg["License", link="http://www.apache.org/licenses/LICENSE-2.0"]
image:https://img.shields.io/maven-central/v/io.smallrye/smallrye-jwt?color=green[]

= SmallRye JWT

SmallRye JWT is a library for implementing the {microprofile-jwt}[{mp-jwt-name}]. Currently it is focused on supporting the MP-JWT 1.1 spec, and primarily deals with the parsing of the JWT string into a JsonWebToken implementation.

In the future, when MP-JWT 2.0 can build on the JSR-375 security APIs, there should be more support for defining the CDI extension and security layer integration.

== Instructions

Compile and install this project:

[source,bash]
----
mvn clean install
----

=== Project structure

* link:implementation[] - Implementation of the {mp-jwt-name} library.
* link:testsuite[] - Test suites
** link:testsuite/basic[] Test suite with basic test cases.
** link:testsuite/tck[] Test suite to run the implementation against the {mp-jwt-name} TCK.
* link:doc[] - Project documentation.

=== Contributing

Please refer to our Wiki for the https://github.com/smallrye/smallrye-parent/wiki[Contribution Guidelines].

=== Links

* http://github.com/smallrye/smallrye-jwt/[Project Homepage]
* {microprofile-jwt}[{mp-jwt-name}]
* https://smallrye.io/docs/smallrye-jwt/index.html[Documentation]
